# PBS configuration
queue: expressbw
project: e14
walltime: 1:00:00
jobname: 1deg_jra55_ryf
ncpus: 252
mem: 500GB
shortpath: /short/e14

# Model configuration
name: common
model: access-om2
input:
#    - /short/e14/rmh561/access-om2/input/fatITF
    - /short/public/access-om2/input_236a3011/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/public/access-om2/bin/yatm_b6caeab.exe
      input: /short/public/access-om2/input_236a3011/yatm_1deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/e14/rmh561/access-om2/bin/fms_ACCESS-OM_1c1f23e_libaccessom2_b6caeab.x
      input:
#         - /short/e14/rmh561/access-om2/input/fatITF/mom_1deg
         - /short/public/access-om2/input_236a3011/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /short/public/access-om2/bin/cice_auscom_360x300_24p_47650cc_libaccessom2_b6caeab.exe
      input: 
#         - /short/e14/rmh561/access-om2/input/fatITF/cice_1deg
         - /short/public/access-om2/input_236a3011/cice_1deg
      ncpus: 24

# Collation
collate:
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /short/public/access-om2/bin/mppnccombine

# Misc
runlog: True
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread -W umask=027
platform:
    nodesize: 28
# postscript: sync_output_to_gdata.sh
