format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/accessom2_restart.nml
  hashes:
    binhash: ed8846c20e3464efd276232eaa9ac8fb
    md5: 70a81629b4c2d0118d51a8a2d20d49b7
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/grid.nc
  hashes:
    binhash: 450e3c05167001596aa00d306636fbef
    md5: 1213e346055ee073fe33dc12578d99c6
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/i2o.nc
  hashes:
    binhash: 8de1bb6085c7f64f1a4daed940eb7883
    md5: 8442cf013776264273e43b425ea62cea
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/ice.restart_file
  hashes:
    binhash: 8973d9f2b63da1efe2ddcf6f4b535e6d
    md5: ae6800691f8375616ab32df9ac364576
work/ice/RESTART/iced.2201-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2201-01-01-00000.nc
  hashes:
    binhash: 0b3b7a0543bf4d0de6c9026673dfd670
    md5: f65a92a9ad65eb554c6bb2c1f05848b2
work/ice/RESTART/iced.2202-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2202-01-01-00000.nc
  hashes:
    binhash: 638a3fc3c557556230d7496190e8e9f2
    md5: 8794cb457122723caf6d563defbd25ee
work/ice/RESTART/iced.2203-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2203-01-01-00000.nc
  hashes:
    binhash: e55379d72e19cf3f25ef340e9af61a8a
    md5: a62bd106d51a10048fde92d526a99198
work/ice/RESTART/iced.2204-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2204-01-01-00000.nc
  hashes:
    binhash: 66efb113b90ce6f818563df07ba9740e
    md5: 850627e6c3e6ce65f918a97db9e4c36e
work/ice/RESTART/iced.2205-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2205-01-01-00000.nc
  hashes:
    binhash: 77e1e4f986e6d33c6701077faf078131
    md5: 85347d6a1953a489c4e8e9990541da8f
work/ice/RESTART/iced.2206-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2206-01-01-00000.nc
  hashes:
    binhash: dabca9d365a933a0b9ffc7fbc17028c6
    md5: 7f3f862b21c2f17cfc0aba21621f385c
work/ice/RESTART/iced.2207-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2207-01-01-00000.nc
  hashes:
    binhash: 527beb11637f5d8eb20468414d732d89
    md5: 0781ae40605b9cf815d83619481e90af
work/ice/RESTART/iced.2208-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2208-01-01-00000.nc
  hashes:
    binhash: 69350a92e6631d268ec0c95684a21b66
    md5: 123ad191d13339c02825b5bfb53a8f10
work/ice/RESTART/iced.2209-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2209-01-01-00000.nc
  hashes:
    binhash: 7761ff8247f703f300a94fdc77d0afc5
    md5: 4da36878eb73ac2d820a1cedd82ef691
work/ice/RESTART/iced.2210-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/iced.2210-01-01-00000.nc
  hashes:
    binhash: da4bc1f141d044a11f1045e8ce523a4f
    md5: dc7e70c7f9bafbeb7f371af6d3e0f765
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/kmt.nc
  hashes:
    binhash: feb30ec7f402a6d954030db7ef08b276
    md5: a5a7b4be90ec06044588b623d555c4ad
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/monthly_sstsss.nc
  hashes:
    binhash: bf71cc3522f22b794b4e839d4f040fca
    md5: 323d4c605f83f4d7d3126da70153c2ed
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/o2i.nc
  hashes:
    binhash: 226a3496a171b5ad5bc0e2809b0a1ad7
    md5: e9050efa02243619d141ce3d9f50135f
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/sicemass.nc
  hashes:
    binhash: 2409173a122a10ca33d43469f1350d42
    md5: 298749036fb166cd73115f54c3867736
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ice/u_star.nc
  hashes:
    binhash: dd417c13c6cdf6f26327a7b72635be18
    md5: 2b6b8cb7e0bc2534824f5e7e19dd2c41
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_age.res.nc
  hashes:
    binhash: bbd63a860af88dcb3fd0e2e2e750a358
    md5: 227928d1935cdd68842e70d24743467d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 89076076f96704959369034d84a3a42b
    md5: 9aa9f5f64eb3a504f6c913dc19cf9d70
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 492b427301e1d92b7f243ee1b006cc24
    md5: ffc5265decb9e9aeda17bb35ae0a7da4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_density.res.nc
  hashes:
    binhash: 86a69ae8e39d9ca1eff055861867ffc1
    md5: 34a402a7a885a8be2fc0c6abaca12bf2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8690f68247f9a410404ba170c4e84a64
    md5: a2f91e72c9ced16b71d959fb91262eaf
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2b2b3b176c64b03eb8c875098b5c17dd
    md5: 2be62d9be6f1e0d97c72bd57351ea38a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d4b43163e873c4ca26a6b3718d63a0fa
    md5: fc7617a211b1df78b22f8f024a6a94b0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e178059dde18035d848e91b1fde1c362
    md5: 2f43db54aee4ad4def6027fe5cfa5f66
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ef4d03a202a4c8c2fbdf4f98cab27ffd
    md5: a851fd784f7e415aaa8273f26b1645b2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c9efc5275f239163495bfdb707c150bc
    md5: 4b5d3950f2a6018b220c80deef40e85c
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_solo.res
  hashes:
    binhash: d6e4928f256f3f1f4cfaf580fcfcc45e
    md5: 510cc52be050311898f1eef2f6230b6e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bd0c9dbfc0fe8573ccc2eb2a787cee6e
    md5: eb4bcf951f9e2e85667f32127647f988
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c0a7d43f244b8cab0b89fd406326b58c
    md5: 93b642524867ba5030b5ebcde0039fc7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_tracer.res
  hashes:
    binhash: a076cdc6006ea5de237076cfc45fd0ae
    md5: 20b2d2bad00d859c3ab111e3644a4fd7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 689a213dd512e0b7637cc832526c997c
    md5: 7ed1ab4d9c4d3b60569001ab6b031609
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/1deg_jra55_ryf_fatITF_cont/restart030/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1fd3324af771840b57df6c4793912ecf
    md5: 1344b7213a49c53d3d44d2662ee74150
